name: Build REPOWebListener

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Add NuGet Sources
      run: |
        dotnet nuget add source https://nuget.bepinex.dev/v3/index.json --name BepInEx
        dotnet nuget add source https://nuget.windows10ce.com/nuget/v3/index.json --name Windows10CE

    - name: Restore dependencies
      run: dotnet restore

    - name: Build REPOWebListener.dll
      run: dotnet build --no-restore --configuration Release

    - name: Package Thunderstore zip
      run: |
        mkdir -p ts_output/BepInEx/plugins

        # Copy the built DLL
        find . -name "REPOWebListener.dll" -exec cp {} ts_output/BepInEx/plugins/ \;

        # Copy manifest, changelog, and icon directly from repo
        cp manifest.json changelog.md icon.png ts_output/

        # Create the Thunderstore zip
        cd ts_output
        zip -r ../PencilFoxStudios-REPOWebListener.zip .
        cd ..

    - name: Upload Thunderstore Package
      uses: actions/upload-artifact@v4
      with:
        name: Thunderstore-Package
        path: PencilFoxStudios-REPOWebListener.zip
